---
board: [ "nice_nano_v2" ]
shield: [ "Bulwark" ]
#include:
#  - board: nice_nano_v2
 #   shield: Bulwark
    # include:
#  - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#   - board: nice_nano_v2
#     shield: corne_left
#     cmake-args: -DCONFIG_ZMK_USB_LOGGING=y
#     artifact-name: corne_left_with_logging
#
